name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # SERVER

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci

      - name: Run Server Tests
        working-directory: ./server
        run: npm test

      # CLIENT

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm ci

      - name: Run Client Tests
        working-directory: ./client
        run: npm test